// Source of truth for the in-app admin technical docs.
// Mirrors the PDF at /mnt/documents/admin-section-technical-docs.pdf.

export type AdminDoc = {
  label: string;
  route: string;
  what: string;
  how: string;
};

export type AdminDocGroup = {
  label: string;
  items: AdminDoc[];
};

export const ADMIN_DOC_GROUPS: AdminDocGroup[] = [
  {
    label: "Overview",
    items: [
      {
        label: "Dashboard",
        route: "/admin/dashboard",
        what: "High-level health snapshot for the site: indexed pages, recent leads, content pipeline, and quick links into every major tool.",
        how: "Server function aggregates counts from content_pages, host_leads, plan_requests, etc. via supabaseAdmin. Renders fast cards with last-N metrics; safe-fallbacks to zero if a query fails.",
      },
      {
        label: "SEO Coach",
        route: "/admin/seo-coach",
        what: "AI assistant that critiques a page or topic and suggests improvements (titles, headings, internal links, EEAT signals).",
        how: "Sends the target slug + content into Lovable AI Gateway (google/gemini-2.5-pro). Returns structured suggestions; nothing is auto-applied.",
      },
    ],
  },
  {
    label: "Content",
    items: [
      { label: "Quick page builder", route: "/admin/quick-page",
        what: "Spin up a single content page from a slug + topic without touching the bulk pipeline.",
        how: "Calls a server fn that drafts the page via Lovable AI, inserts into content_pages with status draft, and returns the new URL." },
      { label: "Generate content", route: "/admin/generate-content",
        what: "Bulk-generate content for many pages at once (host-acq cities, advocacy, hubs).",
        how: "Triggers the generate-content-batch edge function. The function pulls candidate slugs, generates with the chosen model, and writes back to content_pages. Progress shown via polling stats." },
      { label: "Content migration", route: "/admin/content-migration",
        what: "Move/rewrite legacy content into the canonical /p/{slug} structure.",
        how: "Server functions in admin-tools.functions.ts handle slug rewrites, status flips, and 301 alias creation in redirect_aliases." },
      { label: "Bulk page editor", route: "/admin/content-pages",
        what: "Filter/search every row in content_pages, change status (published, pending, draft, scraped), and apply bulk fixes.",
        how: "Loader reads paginated rows via supabaseAdmin (server-only — RLS denies anon). Mutations route through admin server fns; the page-size selector and status filter are query parameters on those fns." },
      { label: "Blog admin", route: "/admin/blog",
        what: "Manage blog_posts: create, enrich (TL;DR, related posts), publish.",
        how: "Uses admin-blog.functions.ts + blog-enrichment.functions.ts. Enrichment calls Lovable AI for summaries and related-post suggestions." },
      { label: "Learning admin", route: "/admin/learning",
        what: "View per-user course progress and completions; drill into a single learner at /admin/learning/$userId.",
        how: "Reads course_completions + learning tables. Issues certificate UIDs via the generate_certificate_uid() DB function." },
      { label: "City heroes", route: "/admin/cities-heroes",
        what: "Backfill and review hero images for the 5,100+ city pages.",
        how: "Stores images in the city-heroes public storage bucket. Backfill server fn uses Unsplash (UNSPLASH_ACCESS_KEY) with deterministic queries per city." },
      { label: "Data export", route: "/admin/data-export",
        what: "Export tables to CSV (leads, pages, blog, etc.) for offline analysis.",
        how: "Server fn streams query results, formats CSV, returns a download URL." },
      { label: "Data import", route: "/admin/data-import",
        what: "Bulk-upload CSV to seed cities, pages, leads, etc.",
        how: "Validates schema, deduplicates by slug/email, inserts via supabaseAdmin. Errors are reported per-row, not all-or-nothing." },
    ],
  },
  {
    label: "SEO",
    items: [
      { label: "Competitor radar", route: "/admin/competitor-radar",
        what: "Surfaces competitor URLs ranking for keywords we should own.",
        how: "Pulls SERP data via SERPAPI_KEY, joins against our content_pages coverage, flags gaps." },
      { label: "Rank tracker", route: "/admin/rank-tracker",
        what: "Tracks our positions for tracked keywords over time.",
        how: "Cron-fed table of rank snapshots; UI charts deltas. SERPAPI_KEY backs the lookups." },
      { label: "AI page auditor", route: "/admin/page-auditor",
        what: "Audit a single page against EEAT, schema, internal-link, and copy heuristics.",
        how: "Fetches the rendered page, sends to Lovable AI for grading, returns a structured scorecard." },
      { label: "Listing auditor", route: "/admin/listing-auditor",
        what: "Audit Sharetribe listings for missing fields, weak photos, low-quality copy.",
        how: "Reads via admin-listing-audit.functions.ts. Sharetribe SDK fetch through SHARETRIBE_INTEG_CLIENT_ID/SECRET." },
      { label: "Keyword opportunities", route: "/admin/keyword-opportunities",
        what: "GSC-driven list of queries where we rank 5–20 — biggest CTR wins.",
        how: "Reads imported GSC data, filters by impressions/position thresholds, sorts by potential traffic." },
      { label: "Competitor tracker", route: "/admin/competitors",
        what: "Manage the competitor URL list that radar/SERP tooling watches.",
        how: "Simple CRUD on a competitors table; admin-only RLS." },
      { label: "Internal link recommender", route: "/admin/internal-links",
        what: "Suggests new internal links between content pages based on topical overlap.",
        how: "Server fn in internal-links.functions.ts tokenizes pages and scores candidates; admin clicks to apply." },
      { label: "SEO health", route: "/admin/seo-health",
        what: "Site-wide SEO health: titles, descriptions, canonicals, h1 count, schema presence.",
        how: "Runs checks across content_pages rows; reports problems in a table." },
      { label: "Link checker", route: "/admin/link-checker",
        what: "Crawl-style checker that pings outbound + internal links and reports 404s.",
        how: "Uses link-checker.functions.ts (HEAD/GET). Results stored for the dashboard." },
      { label: "Link audit dashboard", route: "/admin/link-audit",
        what: "Aggregated view of broken-link audits across the site.",
        how: "Reads from link-audit-dashboard.functions.ts; groups by source page." },
      { label: "Missing pages (404s)", route: "/admin/missing-pages",
        what: "Logs of /p/* URLs that 404 in production — pure SEO gold for new content.",
        how: "content_404_log table populated by the catch-all route; server fn returns top hits." },
      { label: "Sitemap & indexing", route: "/admin/indexing",
        what: "Inspect sitemap entries, rebuild on demand, push URLs for indexing.",
        how: "Uses sitemap.ts helpers that emit absolute production URLs via getCanonicalUrl. Never includes lovable.app hosts." },
      { label: "GSC import", route: "/admin/gsc-import",
        what: "Import Google Search Console performance data.",
        how: "Accepts a GSC CSV/API payload, normalizes queries, persists for keyword opportunities." },
      { label: "Scrape import", route: "/admin/scrape-import",
        what: "Paste Yelp / Google Maps / BBB / Angi / Houzz / Thumbtack URLs to create pending providers.",
        how: "Each URL goes through adminScrapeProviderUrl (uses FIRECRAWL_API_KEY). Successful scrapes insert into providers with status pending and log to scrape_jobs." },
      { label: "Click report", route: "/admin/click-report",
        what: "Where users actually click on the site — outbound clicks, CTAs, internal nav.",
        how: "Backed by click-report.functions.ts aggregating click events." },
    ],
  },
  {
    label: "Users & Ops",
    items: [
      { label: "Lead inbox", route: "/admin/leads",
        what: "Every host/renter lead in one place: contact, source, notes, follow-up status.",
        how: "Reads host_leads via admin server fn. SMS sequences (5-touch Twilio) are auto-scheduled when a host_lead is inserted." },
      { label: "IG lead hunter", route: "/admin/ig-lead-hunter",
        what: "Find Instagram leads (pool owners, party planners) at scale.",
        how: "ig-lead-hunter.server.ts + Lovable AI for qualification. ig_leads is FORCE-RLS, admin-only, accessed exclusively via supabaseAdmin." },
      { label: "Social lead hunter", route: "/admin/social-lead-hunter",
        what: "Cross-platform social lead discovery (beyond IG).",
        how: "Validates URLs via social-url-validator.server.ts, persists to social leads table; same admin-only pattern." },
      { label: "Email branding", route: "/admin/email-branding",
        what: "Manage branded transactional email templates (logo, colors, footer).",
        how: "email-branding.functions.ts writes to email branding settings; templates in src/lib/email-templates/ read those values." },
      { label: "Email verify", route: "/admin/email-verify",
        what: "Verify lead email addresses (deliverable / catch-all / invalid).",
        how: "Calls EmailVerify API (EMAILVERIFY_API_KEY) and persists result on the lead row." },
      { label: "Site footer", route: "/admin/site-footer",
        what: "Edit the production site footer links/columns without redeploying.",
        how: "Reads/writes site-footer config via site-footer.functions.ts; cached and served by the layout." },
      { label: "Directory moderation", route: "/admin/directory",
        what: "Approve/reject pending providers (from scrapes or claims).",
        how: "directory.functions.ts handles status transitions on providers." },
      { label: "Listing claims", route: "/admin/claims",
        what: "Owners claiming a scraped listing — verify and assign ownership.",
        how: "Claim records reference the provider; admin approval flips ownership and fires a transactional email." },
      { label: "Plan requests", route: "/admin/plan-requests",
        what: "Provider plan/payment requests pending review.",
        how: "adminListPlanRequests + adminReviewPlanRequest. Approve applies the requested plan; reject leaves a note. Payment refs are free-text." },
      { label: "Admin team", route: "/admin/team",
        what: "Manage which user_ids hold the admin role.",
        how: "Reads/writes user_roles. Role checks everywhere use the SECURITY DEFINER has_role(uid, 'admin') function — never a client-side check." },
    ],
  },
];

export const ADMIN_DOC_CROSS_CUTTING: { title: string; body: string }[] = [
  { title: "Authentication & access",
    body: "Every /admin/* route's beforeLoad calls checkAdminRole() (server fn). Non-admins are redirected to /admin/no-access. The check uses the SECURITY DEFINER has_role() SQL function against user_roles — admin status is never trusted from the client." },
  { title: "Server-only data access",
    body: "Privileged tables (content_pages, ig_leads, host_leads, sms_*) FORCE RLS and revoke anon/authenticated grants. All reads/writes go through supabaseAdmin inside *.functions.ts / *.server.ts. The browser Supabase client cannot read them." },
  { title: "AI calls",
    body: "Generation/critique tools call the Lovable AI Gateway — no extra API key required. Default models: google/gemini-2.5-pro for long-form generation, gemini-2.5-flash for quick critiques." },
  { title: "External integrations",
    body: "Sharetribe (SHARETRIBE_*), Twilio SMS (TWILIO_API_KEY), Firecrawl scrape (FIRECRAWL_API_KEY), SerpAPI (SERPAPI_KEY), EmailIt (EMAILIT_API_KEY), EmailVerify (EMAILVERIFY_API_KEY), Unsplash (UNSPLASH_ACCESS_KEY), People Data Labs (PDL_API_KEY), BatchData (BATCHDATA_API_KEY). All read inside .handler(), never at module scope." },
  { title: "SMS sequence",
    body: "Inserting into host_leads auto-schedules a 5-touch Twilio sequence at 0m / 1d / 3d / 7d / 14d. Inbound STOP/START handled at /api/public/hooks/twilio-inbound. A cron sender drains the schedule." },
  { title: "Sitemaps & canonical URLs",
    body: "All user-facing URLs flow through getCanonicalOrigin(request) / getCanonicalUrl(request, path), which read X-Forwarded-Host. Sitemaps emit absolute https://www.poolrentalnearme.com URLs only — never lovable.app." },
  { title: "Defensive rendering",
    body: "Every admin server fn returns a typed empty/fallback shape on error, so admin pages render even if a query fails. Errors are surfaced inline rather than crashing the route." },
];
