/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as ApiPublicSitemapByHostRouteImport } from './routes/api/public/sitemap-by-host'
import { Route as ApiPublicPageLookupRouteImport } from './routes/api/public/page-lookup'
import { Route as ApiPublicDomainTokenRouteImport } from './routes/api/public/domain-token'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppSeoCoachRouteImport } from './routes/_authenticated/app.seo-coach'
import { Route as AuthenticatedAppOnboardingRouteImport } from './routes/_authenticated/app.onboarding'
import { Route as AuthenticatedAppBillingRouteImport } from './routes/_authenticated/app.billing'
import { Route as ApiPublicHooksSyncSharetribeRouteImport } from './routes/api/public/hooks/sync-sharetribe'
import { Route as ApiPublicHooksCanonicalAuditRouteImport } from './routes/api/public/hooks/canonical-audit'
import { Route as AuthenticatedAppSettingsDomainsRouteImport } from './routes/_authenticated/app.settings.domains'
import { Route as AuthenticatedAppSettingsApiKeysRouteImport } from './routes/_authenticated/app.settings.api-keys'
import { Route as AuthenticatedAppSeoSitemapRouteImport } from './routes/_authenticated/app.seo.sitemap'
import { Route as AuthenticatedAppSeoScrapeImportRouteImport } from './routes/_authenticated/app.seo.scrape-import'
import { Route as AuthenticatedAppSeoRankTrackerRouteImport } from './routes/_authenticated/app.seo.rank-tracker'
import { Route as AuthenticatedAppSeoPageAuditorRouteImport } from './routes/_authenticated/app.seo.page-auditor'
import { Route as AuthenticatedAppSeoMissingPagesRouteImport } from './routes/_authenticated/app.seo.missing-pages'
import { Route as AuthenticatedAppSeoListingAuditorRouteImport } from './routes/_authenticated/app.seo.listing-auditor'
import { Route as AuthenticatedAppSeoLinkCheckerRouteImport } from './routes/_authenticated/app.seo.link-checker'
import { Route as AuthenticatedAppSeoLinkAuditRouteImport } from './routes/_authenticated/app.seo.link-audit'
import { Route as AuthenticatedAppSeoKeywordOpportunitiesRouteImport } from './routes/_authenticated/app.seo.keyword-opportunities'
import { Route as AuthenticatedAppSeoInternalLinksRouteImport } from './routes/_authenticated/app.seo.internal-links'
import { Route as AuthenticatedAppSeoHealthRouteImport } from './routes/_authenticated/app.seo.health'
import { Route as AuthenticatedAppSeoGscImportRouteImport } from './routes/_authenticated/app.seo.gsc-import'
import { Route as AuthenticatedAppSeoContentHealthRouteImport } from './routes/_authenticated/app.seo.content-health'
import { Route as AuthenticatedAppSeoCompetitorTrackerRouteImport } from './routes/_authenticated/app.seo.competitor-tracker'
import { Route as AuthenticatedAppSeoCompetitorRadarRouteImport } from './routes/_authenticated/app.seo.competitor-radar'
import { Route as AuthenticatedAppSeoClickReportRouteImport } from './routes/_authenticated/app.seo.click-report'
import { Route as AuthenticatedAppSeoCanonicalAuditRouteImport } from './routes/_authenticated/app.seo.canonical-audit'
import { Route as AuthenticatedAppOpsSocialLeadHunterRouteImport } from './routes/_authenticated/app.ops.social-lead-hunter'
import { Route as AuthenticatedAppOpsSiteFooterRouteImport } from './routes/_authenticated/app.ops.site-footer'
import { Route as AuthenticatedAppOpsPlanRequestsRouteImport } from './routes/_authenticated/app.ops.plan-requests'
import { Route as AuthenticatedAppOpsListingClaimsRouteImport } from './routes/_authenticated/app.ops.listing-claims'
import { Route as AuthenticatedAppOpsLeadInboxRouteImport } from './routes/_authenticated/app.ops.lead-inbox'
import { Route as AuthenticatedAppOpsIgLeadHunterRouteImport } from './routes/_authenticated/app.ops.ig-lead-hunter'
import { Route as AuthenticatedAppOpsEmailVerifyRouteImport } from './routes/_authenticated/app.ops.email-verify'
import { Route as AuthenticatedAppOpsEmailBrandingRouteImport } from './routes/_authenticated/app.ops.email-branding'
import { Route as AuthenticatedAppOpsDirectoryModerationRouteImport } from './routes/_authenticated/app.ops.directory-moderation'
import { Route as AuthenticatedAppOpsAdminTeamRouteImport } from './routes/_authenticated/app.ops.admin-team'
import { Route as AuthenticatedAppContentQuickPageBuilderRouteImport } from './routes/_authenticated/app.content.quick-page-builder'
import { Route as AuthenticatedAppContentMigrationRouteImport } from './routes/_authenticated/app.content.migration'
import { Route as AuthenticatedAppContentLearningRouteImport } from './routes/_authenticated/app.content.learning'
import { Route as AuthenticatedAppContentGenerateRouteImport } from './routes/_authenticated/app.content.generate'
import { Route as AuthenticatedAppContentDataImportRouteImport } from './routes/_authenticated/app.content.data-import'
import { Route as AuthenticatedAppContentDataExportRouteImport } from './routes/_authenticated/app.content.data-export'
import { Route as AuthenticatedAppContentCityHeroesRouteImport } from './routes/_authenticated/app.content.city-heroes'
import { Route as AuthenticatedAppContentBulkEditorRouteImport } from './routes/_authenticated/app.content.bulk-editor'
import { Route as AuthenticatedAppContentBlogRouteImport } from './routes/_authenticated/app.content.blog'
import { Route as AuthenticatedAppSettingsIntegrationsSharetribeRouteImport } from './routes/_authenticated/app.settings.integrations.sharetribe'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicSitemapByHostRoute = ApiPublicSitemapByHostRouteImport.update({
  id: '/api/public/sitemap-by-host',
  path: '/api/public/sitemap-by-host',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPageLookupRoute = ApiPublicPageLookupRouteImport.update({
  id: '/api/public/page-lookup',
  path: '/api/public/page-lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDomainTokenRoute = ApiPublicDomainTokenRouteImport.update({
  id: '/api/public/domain-token',
  path: '/api/public/domain-token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSeoCoachRoute =
  AuthenticatedAppSeoCoachRouteImport.update({
    id: '/seo-coach',
    path: '/seo-coach',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOnboardingRoute =
  AuthenticatedAppOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBillingRoute = AuthenticatedAppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicHooksSyncSharetribeRoute =
  ApiPublicHooksSyncSharetribeRouteImport.update({
    id: '/api/public/hooks/sync-sharetribe',
    path: '/api/public/hooks/sync-sharetribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCanonicalAuditRoute =
  ApiPublicHooksCanonicalAuditRouteImport.update({
    id: '/api/public/hooks/canonical-audit',
    path: '/api/public/hooks/canonical-audit',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppSettingsDomainsRoute =
  AuthenticatedAppSettingsDomainsRouteImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppSettingsApiKeysRoute =
  AuthenticatedAppSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppSeoSitemapRoute =
  AuthenticatedAppSeoSitemapRouteImport.update({
    id: '/seo/sitemap',
    path: '/seo/sitemap',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSeoScrapeImportRoute =
  AuthenticatedAppSeoScrapeImportRouteImport.update({
    id: '/seo/scrape-import',
    path: '/seo/scrape-import',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSeoRankTrackerRoute =
  AuthenticatedAppSeoRankTrackerRouteImport.update({
    id: '/seo/rank-tracker',
    path: '/seo/rank-tracker',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSeoPageAuditorRoute =
  AuthenticatedAppSeoPageAuditorRouteImport.update({
    id: '/seo/page-auditor',
    path: '/seo/page-auditor',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSeoMissingPagesRoute =
  AuthenticatedAppSeoMissingPagesRouteImport.update({
    id: '/seo/missing-pages',
    path: '/seo/missing-pages',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSeoListingAuditorRoute =
  AuthenticatedAppSeoListingAuditorRouteImport.update({
    id: '/seo/listing-auditor',
    path: '/seo/listing-auditor',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSeoLinkCheckerRoute =
  AuthenticatedAppSeoLinkCheckerRouteImport.update({
    id: '/seo/link-checker',
    path: '/seo/link-checker',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSeoLinkAuditRoute =
  AuthenticatedAppSeoLinkAuditRouteImport.update({
    id: '/seo/link-audit',
    path: '/seo/link-audit',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSeoKeywordOpportunitiesRoute =
  AuthenticatedAppSeoKeywordOpportunitiesRouteImport.update({
    id: '/seo/keyword-opportunities',
    path: '/seo/keyword-opportunities',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSeoInternalLinksRoute =
  AuthenticatedAppSeoInternalLinksRouteImport.update({
    id: '/seo/internal-links',
    path: '/seo/internal-links',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSeoHealthRoute =
  AuthenticatedAppSeoHealthRouteImport.update({
    id: '/seo/health',
    path: '/seo/health',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSeoGscImportRoute =
  AuthenticatedAppSeoGscImportRouteImport.update({
    id: '/seo/gsc-import',
    path: '/seo/gsc-import',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSeoContentHealthRoute =
  AuthenticatedAppSeoContentHealthRouteImport.update({
    id: '/seo/content-health',
    path: '/seo/content-health',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSeoCompetitorTrackerRoute =
  AuthenticatedAppSeoCompetitorTrackerRouteImport.update({
    id: '/seo/competitor-tracker',
    path: '/seo/competitor-tracker',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSeoCompetitorRadarRoute =
  AuthenticatedAppSeoCompetitorRadarRouteImport.update({
    id: '/seo/competitor-radar',
    path: '/seo/competitor-radar',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSeoClickReportRoute =
  AuthenticatedAppSeoClickReportRouteImport.update({
    id: '/seo/click-report',
    path: '/seo/click-report',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSeoCanonicalAuditRoute =
  AuthenticatedAppSeoCanonicalAuditRouteImport.update({
    id: '/seo/canonical-audit',
    path: '/seo/canonical-audit',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOpsSocialLeadHunterRoute =
  AuthenticatedAppOpsSocialLeadHunterRouteImport.update({
    id: '/ops/social-lead-hunter',
    path: '/ops/social-lead-hunter',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOpsSiteFooterRoute =
  AuthenticatedAppOpsSiteFooterRouteImport.update({
    id: '/ops/site-footer',
    path: '/ops/site-footer',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOpsPlanRequestsRoute =
  AuthenticatedAppOpsPlanRequestsRouteImport.update({
    id: '/ops/plan-requests',
    path: '/ops/plan-requests',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOpsListingClaimsRoute =
  AuthenticatedAppOpsListingClaimsRouteImport.update({
    id: '/ops/listing-claims',
    path: '/ops/listing-claims',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOpsLeadInboxRoute =
  AuthenticatedAppOpsLeadInboxRouteImport.update({
    id: '/ops/lead-inbox',
    path: '/ops/lead-inbox',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOpsIgLeadHunterRoute =
  AuthenticatedAppOpsIgLeadHunterRouteImport.update({
    id: '/ops/ig-lead-hunter',
    path: '/ops/ig-lead-hunter',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOpsEmailVerifyRoute =
  AuthenticatedAppOpsEmailVerifyRouteImport.update({
    id: '/ops/email-verify',
    path: '/ops/email-verify',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOpsEmailBrandingRoute =
  AuthenticatedAppOpsEmailBrandingRouteImport.update({
    id: '/ops/email-branding',
    path: '/ops/email-branding',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOpsDirectoryModerationRoute =
  AuthenticatedAppOpsDirectoryModerationRouteImport.update({
    id: '/ops/directory-moderation',
    path: '/ops/directory-moderation',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOpsAdminTeamRoute =
  AuthenticatedAppOpsAdminTeamRouteImport.update({
    id: '/ops/admin-team',
    path: '/ops/admin-team',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppContentQuickPageBuilderRoute =
  AuthenticatedAppContentQuickPageBuilderRouteImport.update({
    id: '/content/quick-page-builder',
    path: '/content/quick-page-builder',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppContentMigrationRoute =
  AuthenticatedAppContentMigrationRouteImport.update({
    id: '/content/migration',
    path: '/content/migration',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppContentLearningRoute =
  AuthenticatedAppContentLearningRouteImport.update({
    id: '/content/learning',
    path: '/content/learning',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppContentGenerateRoute =
  AuthenticatedAppContentGenerateRouteImport.update({
    id: '/content/generate',
    path: '/content/generate',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppContentDataImportRoute =
  AuthenticatedAppContentDataImportRouteImport.update({
    id: '/content/data-import',
    path: '/content/data-import',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppContentDataExportRoute =
  AuthenticatedAppContentDataExportRouteImport.update({
    id: '/content/data-export',
    path: '/content/data-export',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppContentCityHeroesRoute =
  AuthenticatedAppContentCityHeroesRouteImport.update({
    id: '/content/city-heroes',
    path: '/content/city-heroes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppContentBulkEditorRoute =
  AuthenticatedAppContentBulkEditorRouteImport.update({
    id: '/content/bulk-editor',
    path: '/content/bulk-editor',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppContentBlogRoute =
  AuthenticatedAppContentBlogRouteImport.update({
    id: '/content/blog',
    path: '/content/blog',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsIntegrationsSharetribeRoute =
  AuthenticatedAppSettingsIntegrationsSharetribeRouteImport.update({
    id: '/integrations/sharetribe',
    path: '/integrations/sharetribe',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/seo-coach': typeof AuthenticatedAppSeoCoachRoute
  '/app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/api/public/domain-token': typeof ApiPublicDomainTokenRoute
  '/api/public/page-lookup': typeof ApiPublicPageLookupRoute
  '/api/public/sitemap-by-host': typeof ApiPublicSitemapByHostRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/content/blog': typeof AuthenticatedAppContentBlogRoute
  '/app/content/bulk-editor': typeof AuthenticatedAppContentBulkEditorRoute
  '/app/content/city-heroes': typeof AuthenticatedAppContentCityHeroesRoute
  '/app/content/data-export': typeof AuthenticatedAppContentDataExportRoute
  '/app/content/data-import': typeof AuthenticatedAppContentDataImportRoute
  '/app/content/generate': typeof AuthenticatedAppContentGenerateRoute
  '/app/content/learning': typeof AuthenticatedAppContentLearningRoute
  '/app/content/migration': typeof AuthenticatedAppContentMigrationRoute
  '/app/content/quick-page-builder': typeof AuthenticatedAppContentQuickPageBuilderRoute
  '/app/ops/admin-team': typeof AuthenticatedAppOpsAdminTeamRoute
  '/app/ops/directory-moderation': typeof AuthenticatedAppOpsDirectoryModerationRoute
  '/app/ops/email-branding': typeof AuthenticatedAppOpsEmailBrandingRoute
  '/app/ops/email-verify': typeof AuthenticatedAppOpsEmailVerifyRoute
  '/app/ops/ig-lead-hunter': typeof AuthenticatedAppOpsIgLeadHunterRoute
  '/app/ops/lead-inbox': typeof AuthenticatedAppOpsLeadInboxRoute
  '/app/ops/listing-claims': typeof AuthenticatedAppOpsListingClaimsRoute
  '/app/ops/plan-requests': typeof AuthenticatedAppOpsPlanRequestsRoute
  '/app/ops/site-footer': typeof AuthenticatedAppOpsSiteFooterRoute
  '/app/ops/social-lead-hunter': typeof AuthenticatedAppOpsSocialLeadHunterRoute
  '/app/seo/canonical-audit': typeof AuthenticatedAppSeoCanonicalAuditRoute
  '/app/seo/click-report': typeof AuthenticatedAppSeoClickReportRoute
  '/app/seo/competitor-radar': typeof AuthenticatedAppSeoCompetitorRadarRoute
  '/app/seo/competitor-tracker': typeof AuthenticatedAppSeoCompetitorTrackerRoute
  '/app/seo/content-health': typeof AuthenticatedAppSeoContentHealthRoute
  '/app/seo/gsc-import': typeof AuthenticatedAppSeoGscImportRoute
  '/app/seo/health': typeof AuthenticatedAppSeoHealthRoute
  '/app/seo/internal-links': typeof AuthenticatedAppSeoInternalLinksRoute
  '/app/seo/keyword-opportunities': typeof AuthenticatedAppSeoKeywordOpportunitiesRoute
  '/app/seo/link-audit': typeof AuthenticatedAppSeoLinkAuditRoute
  '/app/seo/link-checker': typeof AuthenticatedAppSeoLinkCheckerRoute
  '/app/seo/listing-auditor': typeof AuthenticatedAppSeoListingAuditorRoute
  '/app/seo/missing-pages': typeof AuthenticatedAppSeoMissingPagesRoute
  '/app/seo/page-auditor': typeof AuthenticatedAppSeoPageAuditorRoute
  '/app/seo/rank-tracker': typeof AuthenticatedAppSeoRankTrackerRoute
  '/app/seo/scrape-import': typeof AuthenticatedAppSeoScrapeImportRoute
  '/app/seo/sitemap': typeof AuthenticatedAppSeoSitemapRoute
  '/app/settings/api-keys': typeof AuthenticatedAppSettingsApiKeysRoute
  '/app/settings/domains': typeof AuthenticatedAppSettingsDomainsRoute
  '/api/public/hooks/canonical-audit': typeof ApiPublicHooksCanonicalAuditRoute
  '/api/public/hooks/sync-sharetribe': typeof ApiPublicHooksSyncSharetribeRoute
  '/app/settings/integrations/sharetribe': typeof AuthenticatedAppSettingsIntegrationsSharetribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/seo-coach': typeof AuthenticatedAppSeoCoachRoute
  '/app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/api/public/domain-token': typeof ApiPublicDomainTokenRoute
  '/api/public/page-lookup': typeof ApiPublicPageLookupRoute
  '/api/public/sitemap-by-host': typeof ApiPublicSitemapByHostRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/content/blog': typeof AuthenticatedAppContentBlogRoute
  '/app/content/bulk-editor': typeof AuthenticatedAppContentBulkEditorRoute
  '/app/content/city-heroes': typeof AuthenticatedAppContentCityHeroesRoute
  '/app/content/data-export': typeof AuthenticatedAppContentDataExportRoute
  '/app/content/data-import': typeof AuthenticatedAppContentDataImportRoute
  '/app/content/generate': typeof AuthenticatedAppContentGenerateRoute
  '/app/content/learning': typeof AuthenticatedAppContentLearningRoute
  '/app/content/migration': typeof AuthenticatedAppContentMigrationRoute
  '/app/content/quick-page-builder': typeof AuthenticatedAppContentQuickPageBuilderRoute
  '/app/ops/admin-team': typeof AuthenticatedAppOpsAdminTeamRoute
  '/app/ops/directory-moderation': typeof AuthenticatedAppOpsDirectoryModerationRoute
  '/app/ops/email-branding': typeof AuthenticatedAppOpsEmailBrandingRoute
  '/app/ops/email-verify': typeof AuthenticatedAppOpsEmailVerifyRoute
  '/app/ops/ig-lead-hunter': typeof AuthenticatedAppOpsIgLeadHunterRoute
  '/app/ops/lead-inbox': typeof AuthenticatedAppOpsLeadInboxRoute
  '/app/ops/listing-claims': typeof AuthenticatedAppOpsListingClaimsRoute
  '/app/ops/plan-requests': typeof AuthenticatedAppOpsPlanRequestsRoute
  '/app/ops/site-footer': typeof AuthenticatedAppOpsSiteFooterRoute
  '/app/ops/social-lead-hunter': typeof AuthenticatedAppOpsSocialLeadHunterRoute
  '/app/seo/canonical-audit': typeof AuthenticatedAppSeoCanonicalAuditRoute
  '/app/seo/click-report': typeof AuthenticatedAppSeoClickReportRoute
  '/app/seo/competitor-radar': typeof AuthenticatedAppSeoCompetitorRadarRoute
  '/app/seo/competitor-tracker': typeof AuthenticatedAppSeoCompetitorTrackerRoute
  '/app/seo/content-health': typeof AuthenticatedAppSeoContentHealthRoute
  '/app/seo/gsc-import': typeof AuthenticatedAppSeoGscImportRoute
  '/app/seo/health': typeof AuthenticatedAppSeoHealthRoute
  '/app/seo/internal-links': typeof AuthenticatedAppSeoInternalLinksRoute
  '/app/seo/keyword-opportunities': typeof AuthenticatedAppSeoKeywordOpportunitiesRoute
  '/app/seo/link-audit': typeof AuthenticatedAppSeoLinkAuditRoute
  '/app/seo/link-checker': typeof AuthenticatedAppSeoLinkCheckerRoute
  '/app/seo/listing-auditor': typeof AuthenticatedAppSeoListingAuditorRoute
  '/app/seo/missing-pages': typeof AuthenticatedAppSeoMissingPagesRoute
  '/app/seo/page-auditor': typeof AuthenticatedAppSeoPageAuditorRoute
  '/app/seo/rank-tracker': typeof AuthenticatedAppSeoRankTrackerRoute
  '/app/seo/scrape-import': typeof AuthenticatedAppSeoScrapeImportRoute
  '/app/seo/sitemap': typeof AuthenticatedAppSeoSitemapRoute
  '/app/settings/api-keys': typeof AuthenticatedAppSettingsApiKeysRoute
  '/app/settings/domains': typeof AuthenticatedAppSettingsDomainsRoute
  '/api/public/hooks/canonical-audit': typeof ApiPublicHooksCanonicalAuditRoute
  '/api/public/hooks/sync-sharetribe': typeof ApiPublicHooksSyncSharetribeRoute
  '/app/settings/integrations/sharetribe': typeof AuthenticatedAppSettingsIntegrationsSharetribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/billing': typeof AuthenticatedAppBillingRoute
  '/_authenticated/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/_authenticated/app/seo-coach': typeof AuthenticatedAppSeoCoachRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/api/public/domain-token': typeof ApiPublicDomainTokenRoute
  '/api/public/page-lookup': typeof ApiPublicPageLookupRoute
  '/api/public/sitemap-by-host': typeof ApiPublicSitemapByHostRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/content/blog': typeof AuthenticatedAppContentBlogRoute
  '/_authenticated/app/content/bulk-editor': typeof AuthenticatedAppContentBulkEditorRoute
  '/_authenticated/app/content/city-heroes': typeof AuthenticatedAppContentCityHeroesRoute
  '/_authenticated/app/content/data-export': typeof AuthenticatedAppContentDataExportRoute
  '/_authenticated/app/content/data-import': typeof AuthenticatedAppContentDataImportRoute
  '/_authenticated/app/content/generate': typeof AuthenticatedAppContentGenerateRoute
  '/_authenticated/app/content/learning': typeof AuthenticatedAppContentLearningRoute
  '/_authenticated/app/content/migration': typeof AuthenticatedAppContentMigrationRoute
  '/_authenticated/app/content/quick-page-builder': typeof AuthenticatedAppContentQuickPageBuilderRoute
  '/_authenticated/app/ops/admin-team': typeof AuthenticatedAppOpsAdminTeamRoute
  '/_authenticated/app/ops/directory-moderation': typeof AuthenticatedAppOpsDirectoryModerationRoute
  '/_authenticated/app/ops/email-branding': typeof AuthenticatedAppOpsEmailBrandingRoute
  '/_authenticated/app/ops/email-verify': typeof AuthenticatedAppOpsEmailVerifyRoute
  '/_authenticated/app/ops/ig-lead-hunter': typeof AuthenticatedAppOpsIgLeadHunterRoute
  '/_authenticated/app/ops/lead-inbox': typeof AuthenticatedAppOpsLeadInboxRoute
  '/_authenticated/app/ops/listing-claims': typeof AuthenticatedAppOpsListingClaimsRoute
  '/_authenticated/app/ops/plan-requests': typeof AuthenticatedAppOpsPlanRequestsRoute
  '/_authenticated/app/ops/site-footer': typeof AuthenticatedAppOpsSiteFooterRoute
  '/_authenticated/app/ops/social-lead-hunter': typeof AuthenticatedAppOpsSocialLeadHunterRoute
  '/_authenticated/app/seo/canonical-audit': typeof AuthenticatedAppSeoCanonicalAuditRoute
  '/_authenticated/app/seo/click-report': typeof AuthenticatedAppSeoClickReportRoute
  '/_authenticated/app/seo/competitor-radar': typeof AuthenticatedAppSeoCompetitorRadarRoute
  '/_authenticated/app/seo/competitor-tracker': typeof AuthenticatedAppSeoCompetitorTrackerRoute
  '/_authenticated/app/seo/content-health': typeof AuthenticatedAppSeoContentHealthRoute
  '/_authenticated/app/seo/gsc-import': typeof AuthenticatedAppSeoGscImportRoute
  '/_authenticated/app/seo/health': typeof AuthenticatedAppSeoHealthRoute
  '/_authenticated/app/seo/internal-links': typeof AuthenticatedAppSeoInternalLinksRoute
  '/_authenticated/app/seo/keyword-opportunities': typeof AuthenticatedAppSeoKeywordOpportunitiesRoute
  '/_authenticated/app/seo/link-audit': typeof AuthenticatedAppSeoLinkAuditRoute
  '/_authenticated/app/seo/link-checker': typeof AuthenticatedAppSeoLinkCheckerRoute
  '/_authenticated/app/seo/listing-auditor': typeof AuthenticatedAppSeoListingAuditorRoute
  '/_authenticated/app/seo/missing-pages': typeof AuthenticatedAppSeoMissingPagesRoute
  '/_authenticated/app/seo/page-auditor': typeof AuthenticatedAppSeoPageAuditorRoute
  '/_authenticated/app/seo/rank-tracker': typeof AuthenticatedAppSeoRankTrackerRoute
  '/_authenticated/app/seo/scrape-import': typeof AuthenticatedAppSeoScrapeImportRoute
  '/_authenticated/app/seo/sitemap': typeof AuthenticatedAppSeoSitemapRoute
  '/_authenticated/app/settings/api-keys': typeof AuthenticatedAppSettingsApiKeysRoute
  '/_authenticated/app/settings/domains': typeof AuthenticatedAppSettingsDomainsRoute
  '/api/public/hooks/canonical-audit': typeof ApiPublicHooksCanonicalAuditRoute
  '/api/public/hooks/sync-sharetribe': typeof ApiPublicHooksSyncSharetribeRoute
  '/_authenticated/app/settings/integrations/sharetribe': typeof AuthenticatedAppSettingsIntegrationsSharetribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/app'
    | '/app/billing'
    | '/app/onboarding'
    | '/app/seo-coach'
    | '/app/settings'
    | '/api/public/domain-token'
    | '/api/public/page-lookup'
    | '/api/public/sitemap-by-host'
    | '/app/'
    | '/app/content/blog'
    | '/app/content/bulk-editor'
    | '/app/content/city-heroes'
    | '/app/content/data-export'
    | '/app/content/data-import'
    | '/app/content/generate'
    | '/app/content/learning'
    | '/app/content/migration'
    | '/app/content/quick-page-builder'
    | '/app/ops/admin-team'
    | '/app/ops/directory-moderation'
    | '/app/ops/email-branding'
    | '/app/ops/email-verify'
    | '/app/ops/ig-lead-hunter'
    | '/app/ops/lead-inbox'
    | '/app/ops/listing-claims'
    | '/app/ops/plan-requests'
    | '/app/ops/site-footer'
    | '/app/ops/social-lead-hunter'
    | '/app/seo/canonical-audit'
    | '/app/seo/click-report'
    | '/app/seo/competitor-radar'
    | '/app/seo/competitor-tracker'
    | '/app/seo/content-health'
    | '/app/seo/gsc-import'
    | '/app/seo/health'
    | '/app/seo/internal-links'
    | '/app/seo/keyword-opportunities'
    | '/app/seo/link-audit'
    | '/app/seo/link-checker'
    | '/app/seo/listing-auditor'
    | '/app/seo/missing-pages'
    | '/app/seo/page-auditor'
    | '/app/seo/rank-tracker'
    | '/app/seo/scrape-import'
    | '/app/seo/sitemap'
    | '/app/settings/api-keys'
    | '/app/settings/domains'
    | '/api/public/hooks/canonical-audit'
    | '/api/public/hooks/sync-sharetribe'
    | '/app/settings/integrations/sharetribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/app/billing'
    | '/app/onboarding'
    | '/app/seo-coach'
    | '/app/settings'
    | '/api/public/domain-token'
    | '/api/public/page-lookup'
    | '/api/public/sitemap-by-host'
    | '/app'
    | '/app/content/blog'
    | '/app/content/bulk-editor'
    | '/app/content/city-heroes'
    | '/app/content/data-export'
    | '/app/content/data-import'
    | '/app/content/generate'
    | '/app/content/learning'
    | '/app/content/migration'
    | '/app/content/quick-page-builder'
    | '/app/ops/admin-team'
    | '/app/ops/directory-moderation'
    | '/app/ops/email-branding'
    | '/app/ops/email-verify'
    | '/app/ops/ig-lead-hunter'
    | '/app/ops/lead-inbox'
    | '/app/ops/listing-claims'
    | '/app/ops/plan-requests'
    | '/app/ops/site-footer'
    | '/app/ops/social-lead-hunter'
    | '/app/seo/canonical-audit'
    | '/app/seo/click-report'
    | '/app/seo/competitor-radar'
    | '/app/seo/competitor-tracker'
    | '/app/seo/content-health'
    | '/app/seo/gsc-import'
    | '/app/seo/health'
    | '/app/seo/internal-links'
    | '/app/seo/keyword-opportunities'
    | '/app/seo/link-audit'
    | '/app/seo/link-checker'
    | '/app/seo/listing-auditor'
    | '/app/seo/missing-pages'
    | '/app/seo/page-auditor'
    | '/app/seo/rank-tracker'
    | '/app/seo/scrape-import'
    | '/app/seo/sitemap'
    | '/app/settings/api-keys'
    | '/app/settings/domains'
    | '/api/public/hooks/canonical-audit'
    | '/api/public/hooks/sync-sharetribe'
    | '/app/settings/integrations/sharetribe'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/_authenticated/app'
    | '/_authenticated/app/billing'
    | '/_authenticated/app/onboarding'
    | '/_authenticated/app/seo-coach'
    | '/_authenticated/app/settings'
    | '/api/public/domain-token'
    | '/api/public/page-lookup'
    | '/api/public/sitemap-by-host'
    | '/_authenticated/app/'
    | '/_authenticated/app/content/blog'
    | '/_authenticated/app/content/bulk-editor'
    | '/_authenticated/app/content/city-heroes'
    | '/_authenticated/app/content/data-export'
    | '/_authenticated/app/content/data-import'
    | '/_authenticated/app/content/generate'
    | '/_authenticated/app/content/learning'
    | '/_authenticated/app/content/migration'
    | '/_authenticated/app/content/quick-page-builder'
    | '/_authenticated/app/ops/admin-team'
    | '/_authenticated/app/ops/directory-moderation'
    | '/_authenticated/app/ops/email-branding'
    | '/_authenticated/app/ops/email-verify'
    | '/_authenticated/app/ops/ig-lead-hunter'
    | '/_authenticated/app/ops/lead-inbox'
    | '/_authenticated/app/ops/listing-claims'
    | '/_authenticated/app/ops/plan-requests'
    | '/_authenticated/app/ops/site-footer'
    | '/_authenticated/app/ops/social-lead-hunter'
    | '/_authenticated/app/seo/canonical-audit'
    | '/_authenticated/app/seo/click-report'
    | '/_authenticated/app/seo/competitor-radar'
    | '/_authenticated/app/seo/competitor-tracker'
    | '/_authenticated/app/seo/content-health'
    | '/_authenticated/app/seo/gsc-import'
    | '/_authenticated/app/seo/health'
    | '/_authenticated/app/seo/internal-links'
    | '/_authenticated/app/seo/keyword-opportunities'
    | '/_authenticated/app/seo/link-audit'
    | '/_authenticated/app/seo/link-checker'
    | '/_authenticated/app/seo/listing-auditor'
    | '/_authenticated/app/seo/missing-pages'
    | '/_authenticated/app/seo/page-auditor'
    | '/_authenticated/app/seo/rank-tracker'
    | '/_authenticated/app/seo/scrape-import'
    | '/_authenticated/app/seo/sitemap'
    | '/_authenticated/app/settings/api-keys'
    | '/_authenticated/app/settings/domains'
    | '/api/public/hooks/canonical-audit'
    | '/api/public/hooks/sync-sharetribe'
    | '/_authenticated/app/settings/integrations/sharetribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicDomainTokenRoute: typeof ApiPublicDomainTokenRoute
  ApiPublicPageLookupRoute: typeof ApiPublicPageLookupRoute
  ApiPublicSitemapByHostRoute: typeof ApiPublicSitemapByHostRoute
  ApiPublicHooksCanonicalAuditRoute: typeof ApiPublicHooksCanonicalAuditRoute
  ApiPublicHooksSyncSharetribeRoute: typeof ApiPublicHooksSyncSharetribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/sitemap-by-host': {
      id: '/api/public/sitemap-by-host'
      path: '/api/public/sitemap-by-host'
      fullPath: '/api/public/sitemap-by-host'
      preLoaderRoute: typeof ApiPublicSitemapByHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/page-lookup': {
      id: '/api/public/page-lookup'
      path: '/api/public/page-lookup'
      fullPath: '/api/public/page-lookup'
      preLoaderRoute: typeof ApiPublicPageLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/domain-token': {
      id: '/api/public/domain-token'
      path: '/api/public/domain-token'
      fullPath: '/api/public/domain-token'
      preLoaderRoute: typeof ApiPublicDomainTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/seo-coach': {
      id: '/_authenticated/app/seo-coach'
      path: '/seo-coach'
      fullPath: '/app/seo-coach'
      preLoaderRoute: typeof AuthenticatedAppSeoCoachRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/onboarding': {
      id: '/_authenticated/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AuthenticatedAppOnboardingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/billing': {
      id: '/_authenticated/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AuthenticatedAppBillingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/hooks/sync-sharetribe': {
      id: '/api/public/hooks/sync-sharetribe'
      path: '/api/public/hooks/sync-sharetribe'
      fullPath: '/api/public/hooks/sync-sharetribe'
      preLoaderRoute: typeof ApiPublicHooksSyncSharetribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/canonical-audit': {
      id: '/api/public/hooks/canonical-audit'
      path: '/api/public/hooks/canonical-audit'
      fullPath: '/api/public/hooks/canonical-audit'
      preLoaderRoute: typeof ApiPublicHooksCanonicalAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/settings/domains': {
      id: '/_authenticated/app/settings/domains'
      path: '/domains'
      fullPath: '/app/settings/domains'
      preLoaderRoute: typeof AuthenticatedAppSettingsDomainsRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/app/settings/api-keys': {
      id: '/_authenticated/app/settings/api-keys'
      path: '/api-keys'
      fullPath: '/app/settings/api-keys'
      preLoaderRoute: typeof AuthenticatedAppSettingsApiKeysRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/app/seo/sitemap': {
      id: '/_authenticated/app/seo/sitemap'
      path: '/seo/sitemap'
      fullPath: '/app/seo/sitemap'
      preLoaderRoute: typeof AuthenticatedAppSeoSitemapRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/seo/scrape-import': {
      id: '/_authenticated/app/seo/scrape-import'
      path: '/seo/scrape-import'
      fullPath: '/app/seo/scrape-import'
      preLoaderRoute: typeof AuthenticatedAppSeoScrapeImportRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/seo/rank-tracker': {
      id: '/_authenticated/app/seo/rank-tracker'
      path: '/seo/rank-tracker'
      fullPath: '/app/seo/rank-tracker'
      preLoaderRoute: typeof AuthenticatedAppSeoRankTrackerRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/seo/page-auditor': {
      id: '/_authenticated/app/seo/page-auditor'
      path: '/seo/page-auditor'
      fullPath: '/app/seo/page-auditor'
      preLoaderRoute: typeof AuthenticatedAppSeoPageAuditorRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/seo/missing-pages': {
      id: '/_authenticated/app/seo/missing-pages'
      path: '/seo/missing-pages'
      fullPath: '/app/seo/missing-pages'
      preLoaderRoute: typeof AuthenticatedAppSeoMissingPagesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/seo/listing-auditor': {
      id: '/_authenticated/app/seo/listing-auditor'
      path: '/seo/listing-auditor'
      fullPath: '/app/seo/listing-auditor'
      preLoaderRoute: typeof AuthenticatedAppSeoListingAuditorRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/seo/link-checker': {
      id: '/_authenticated/app/seo/link-checker'
      path: '/seo/link-checker'
      fullPath: '/app/seo/link-checker'
      preLoaderRoute: typeof AuthenticatedAppSeoLinkCheckerRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/seo/link-audit': {
      id: '/_authenticated/app/seo/link-audit'
      path: '/seo/link-audit'
      fullPath: '/app/seo/link-audit'
      preLoaderRoute: typeof AuthenticatedAppSeoLinkAuditRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/seo/keyword-opportunities': {
      id: '/_authenticated/app/seo/keyword-opportunities'
      path: '/seo/keyword-opportunities'
      fullPath: '/app/seo/keyword-opportunities'
      preLoaderRoute: typeof AuthenticatedAppSeoKeywordOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/seo/internal-links': {
      id: '/_authenticated/app/seo/internal-links'
      path: '/seo/internal-links'
      fullPath: '/app/seo/internal-links'
      preLoaderRoute: typeof AuthenticatedAppSeoInternalLinksRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/seo/health': {
      id: '/_authenticated/app/seo/health'
      path: '/seo/health'
      fullPath: '/app/seo/health'
      preLoaderRoute: typeof AuthenticatedAppSeoHealthRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/seo/gsc-import': {
      id: '/_authenticated/app/seo/gsc-import'
      path: '/seo/gsc-import'
      fullPath: '/app/seo/gsc-import'
      preLoaderRoute: typeof AuthenticatedAppSeoGscImportRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/seo/content-health': {
      id: '/_authenticated/app/seo/content-health'
      path: '/seo/content-health'
      fullPath: '/app/seo/content-health'
      preLoaderRoute: typeof AuthenticatedAppSeoContentHealthRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/seo/competitor-tracker': {
      id: '/_authenticated/app/seo/competitor-tracker'
      path: '/seo/competitor-tracker'
      fullPath: '/app/seo/competitor-tracker'
      preLoaderRoute: typeof AuthenticatedAppSeoCompetitorTrackerRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/seo/competitor-radar': {
      id: '/_authenticated/app/seo/competitor-radar'
      path: '/seo/competitor-radar'
      fullPath: '/app/seo/competitor-radar'
      preLoaderRoute: typeof AuthenticatedAppSeoCompetitorRadarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/seo/click-report': {
      id: '/_authenticated/app/seo/click-report'
      path: '/seo/click-report'
      fullPath: '/app/seo/click-report'
      preLoaderRoute: typeof AuthenticatedAppSeoClickReportRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/seo/canonical-audit': {
      id: '/_authenticated/app/seo/canonical-audit'
      path: '/seo/canonical-audit'
      fullPath: '/app/seo/canonical-audit'
      preLoaderRoute: typeof AuthenticatedAppSeoCanonicalAuditRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ops/social-lead-hunter': {
      id: '/_authenticated/app/ops/social-lead-hunter'
      path: '/ops/social-lead-hunter'
      fullPath: '/app/ops/social-lead-hunter'
      preLoaderRoute: typeof AuthenticatedAppOpsSocialLeadHunterRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ops/site-footer': {
      id: '/_authenticated/app/ops/site-footer'
      path: '/ops/site-footer'
      fullPath: '/app/ops/site-footer'
      preLoaderRoute: typeof AuthenticatedAppOpsSiteFooterRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ops/plan-requests': {
      id: '/_authenticated/app/ops/plan-requests'
      path: '/ops/plan-requests'
      fullPath: '/app/ops/plan-requests'
      preLoaderRoute: typeof AuthenticatedAppOpsPlanRequestsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ops/listing-claims': {
      id: '/_authenticated/app/ops/listing-claims'
      path: '/ops/listing-claims'
      fullPath: '/app/ops/listing-claims'
      preLoaderRoute: typeof AuthenticatedAppOpsListingClaimsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ops/lead-inbox': {
      id: '/_authenticated/app/ops/lead-inbox'
      path: '/ops/lead-inbox'
      fullPath: '/app/ops/lead-inbox'
      preLoaderRoute: typeof AuthenticatedAppOpsLeadInboxRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ops/ig-lead-hunter': {
      id: '/_authenticated/app/ops/ig-lead-hunter'
      path: '/ops/ig-lead-hunter'
      fullPath: '/app/ops/ig-lead-hunter'
      preLoaderRoute: typeof AuthenticatedAppOpsIgLeadHunterRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ops/email-verify': {
      id: '/_authenticated/app/ops/email-verify'
      path: '/ops/email-verify'
      fullPath: '/app/ops/email-verify'
      preLoaderRoute: typeof AuthenticatedAppOpsEmailVerifyRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ops/email-branding': {
      id: '/_authenticated/app/ops/email-branding'
      path: '/ops/email-branding'
      fullPath: '/app/ops/email-branding'
      preLoaderRoute: typeof AuthenticatedAppOpsEmailBrandingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ops/directory-moderation': {
      id: '/_authenticated/app/ops/directory-moderation'
      path: '/ops/directory-moderation'
      fullPath: '/app/ops/directory-moderation'
      preLoaderRoute: typeof AuthenticatedAppOpsDirectoryModerationRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ops/admin-team': {
      id: '/_authenticated/app/ops/admin-team'
      path: '/ops/admin-team'
      fullPath: '/app/ops/admin-team'
      preLoaderRoute: typeof AuthenticatedAppOpsAdminTeamRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/content/quick-page-builder': {
      id: '/_authenticated/app/content/quick-page-builder'
      path: '/content/quick-page-builder'
      fullPath: '/app/content/quick-page-builder'
      preLoaderRoute: typeof AuthenticatedAppContentQuickPageBuilderRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/content/migration': {
      id: '/_authenticated/app/content/migration'
      path: '/content/migration'
      fullPath: '/app/content/migration'
      preLoaderRoute: typeof AuthenticatedAppContentMigrationRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/content/learning': {
      id: '/_authenticated/app/content/learning'
      path: '/content/learning'
      fullPath: '/app/content/learning'
      preLoaderRoute: typeof AuthenticatedAppContentLearningRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/content/generate': {
      id: '/_authenticated/app/content/generate'
      path: '/content/generate'
      fullPath: '/app/content/generate'
      preLoaderRoute: typeof AuthenticatedAppContentGenerateRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/content/data-import': {
      id: '/_authenticated/app/content/data-import'
      path: '/content/data-import'
      fullPath: '/app/content/data-import'
      preLoaderRoute: typeof AuthenticatedAppContentDataImportRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/content/data-export': {
      id: '/_authenticated/app/content/data-export'
      path: '/content/data-export'
      fullPath: '/app/content/data-export'
      preLoaderRoute: typeof AuthenticatedAppContentDataExportRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/content/city-heroes': {
      id: '/_authenticated/app/content/city-heroes'
      path: '/content/city-heroes'
      fullPath: '/app/content/city-heroes'
      preLoaderRoute: typeof AuthenticatedAppContentCityHeroesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/content/bulk-editor': {
      id: '/_authenticated/app/content/bulk-editor'
      path: '/content/bulk-editor'
      fullPath: '/app/content/bulk-editor'
      preLoaderRoute: typeof AuthenticatedAppContentBulkEditorRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/content/blog': {
      id: '/_authenticated/app/content/blog'
      path: '/content/blog'
      fullPath: '/app/content/blog'
      preLoaderRoute: typeof AuthenticatedAppContentBlogRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings/integrations/sharetribe': {
      id: '/_authenticated/app/settings/integrations/sharetribe'
      path: '/integrations/sharetribe'
      fullPath: '/app/settings/integrations/sharetribe'
      preLoaderRoute: typeof AuthenticatedAppSettingsIntegrationsSharetribeRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
  }
}

interface AuthenticatedAppSettingsRouteChildren {
  AuthenticatedAppSettingsApiKeysRoute: typeof AuthenticatedAppSettingsApiKeysRoute
  AuthenticatedAppSettingsDomainsRoute: typeof AuthenticatedAppSettingsDomainsRoute
  AuthenticatedAppSettingsIntegrationsSharetribeRoute: typeof AuthenticatedAppSettingsIntegrationsSharetribeRoute
}

const AuthenticatedAppSettingsRouteChildren: AuthenticatedAppSettingsRouteChildren =
  {
    AuthenticatedAppSettingsApiKeysRoute: AuthenticatedAppSettingsApiKeysRoute,
    AuthenticatedAppSettingsDomainsRoute: AuthenticatedAppSettingsDomainsRoute,
    AuthenticatedAppSettingsIntegrationsSharetribeRoute:
      AuthenticatedAppSettingsIntegrationsSharetribeRoute,
  }

const AuthenticatedAppSettingsRouteWithChildren =
  AuthenticatedAppSettingsRoute._addFileChildren(
    AuthenticatedAppSettingsRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppBillingRoute: typeof AuthenticatedAppBillingRoute
  AuthenticatedAppOnboardingRoute: typeof AuthenticatedAppOnboardingRoute
  AuthenticatedAppSeoCoachRoute: typeof AuthenticatedAppSeoCoachRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRouteWithChildren
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppContentBlogRoute: typeof AuthenticatedAppContentBlogRoute
  AuthenticatedAppContentBulkEditorRoute: typeof AuthenticatedAppContentBulkEditorRoute
  AuthenticatedAppContentCityHeroesRoute: typeof AuthenticatedAppContentCityHeroesRoute
  AuthenticatedAppContentDataExportRoute: typeof AuthenticatedAppContentDataExportRoute
  AuthenticatedAppContentDataImportRoute: typeof AuthenticatedAppContentDataImportRoute
  AuthenticatedAppContentGenerateRoute: typeof AuthenticatedAppContentGenerateRoute
  AuthenticatedAppContentLearningRoute: typeof AuthenticatedAppContentLearningRoute
  AuthenticatedAppContentMigrationRoute: typeof AuthenticatedAppContentMigrationRoute
  AuthenticatedAppContentQuickPageBuilderRoute: typeof AuthenticatedAppContentQuickPageBuilderRoute
  AuthenticatedAppOpsAdminTeamRoute: typeof AuthenticatedAppOpsAdminTeamRoute
  AuthenticatedAppOpsDirectoryModerationRoute: typeof AuthenticatedAppOpsDirectoryModerationRoute
  AuthenticatedAppOpsEmailBrandingRoute: typeof AuthenticatedAppOpsEmailBrandingRoute
  AuthenticatedAppOpsEmailVerifyRoute: typeof AuthenticatedAppOpsEmailVerifyRoute
  AuthenticatedAppOpsIgLeadHunterRoute: typeof AuthenticatedAppOpsIgLeadHunterRoute
  AuthenticatedAppOpsLeadInboxRoute: typeof AuthenticatedAppOpsLeadInboxRoute
  AuthenticatedAppOpsListingClaimsRoute: typeof AuthenticatedAppOpsListingClaimsRoute
  AuthenticatedAppOpsPlanRequestsRoute: typeof AuthenticatedAppOpsPlanRequestsRoute
  AuthenticatedAppOpsSiteFooterRoute: typeof AuthenticatedAppOpsSiteFooterRoute
  AuthenticatedAppOpsSocialLeadHunterRoute: typeof AuthenticatedAppOpsSocialLeadHunterRoute
  AuthenticatedAppSeoCanonicalAuditRoute: typeof AuthenticatedAppSeoCanonicalAuditRoute
  AuthenticatedAppSeoClickReportRoute: typeof AuthenticatedAppSeoClickReportRoute
  AuthenticatedAppSeoCompetitorRadarRoute: typeof AuthenticatedAppSeoCompetitorRadarRoute
  AuthenticatedAppSeoCompetitorTrackerRoute: typeof AuthenticatedAppSeoCompetitorTrackerRoute
  AuthenticatedAppSeoContentHealthRoute: typeof AuthenticatedAppSeoContentHealthRoute
  AuthenticatedAppSeoGscImportRoute: typeof AuthenticatedAppSeoGscImportRoute
  AuthenticatedAppSeoHealthRoute: typeof AuthenticatedAppSeoHealthRoute
  AuthenticatedAppSeoInternalLinksRoute: typeof AuthenticatedAppSeoInternalLinksRoute
  AuthenticatedAppSeoKeywordOpportunitiesRoute: typeof AuthenticatedAppSeoKeywordOpportunitiesRoute
  AuthenticatedAppSeoLinkAuditRoute: typeof AuthenticatedAppSeoLinkAuditRoute
  AuthenticatedAppSeoLinkCheckerRoute: typeof AuthenticatedAppSeoLinkCheckerRoute
  AuthenticatedAppSeoListingAuditorRoute: typeof AuthenticatedAppSeoListingAuditorRoute
  AuthenticatedAppSeoMissingPagesRoute: typeof AuthenticatedAppSeoMissingPagesRoute
  AuthenticatedAppSeoPageAuditorRoute: typeof AuthenticatedAppSeoPageAuditorRoute
  AuthenticatedAppSeoRankTrackerRoute: typeof AuthenticatedAppSeoRankTrackerRoute
  AuthenticatedAppSeoScrapeImportRoute: typeof AuthenticatedAppSeoScrapeImportRoute
  AuthenticatedAppSeoSitemapRoute: typeof AuthenticatedAppSeoSitemapRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppBillingRoute: AuthenticatedAppBillingRoute,
  AuthenticatedAppOnboardingRoute: AuthenticatedAppOnboardingRoute,
  AuthenticatedAppSeoCoachRoute: AuthenticatedAppSeoCoachRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRouteWithChildren,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppContentBlogRoute: AuthenticatedAppContentBlogRoute,
  AuthenticatedAppContentBulkEditorRoute:
    AuthenticatedAppContentBulkEditorRoute,
  AuthenticatedAppContentCityHeroesRoute:
    AuthenticatedAppContentCityHeroesRoute,
  AuthenticatedAppContentDataExportRoute:
    AuthenticatedAppContentDataExportRoute,
  AuthenticatedAppContentDataImportRoute:
    AuthenticatedAppContentDataImportRoute,
  AuthenticatedAppContentGenerateRoute: AuthenticatedAppContentGenerateRoute,
  AuthenticatedAppContentLearningRoute: AuthenticatedAppContentLearningRoute,
  AuthenticatedAppContentMigrationRoute: AuthenticatedAppContentMigrationRoute,
  AuthenticatedAppContentQuickPageBuilderRoute:
    AuthenticatedAppContentQuickPageBuilderRoute,
  AuthenticatedAppOpsAdminTeamRoute: AuthenticatedAppOpsAdminTeamRoute,
  AuthenticatedAppOpsDirectoryModerationRoute:
    AuthenticatedAppOpsDirectoryModerationRoute,
  AuthenticatedAppOpsEmailBrandingRoute: AuthenticatedAppOpsEmailBrandingRoute,
  AuthenticatedAppOpsEmailVerifyRoute: AuthenticatedAppOpsEmailVerifyRoute,
  AuthenticatedAppOpsIgLeadHunterRoute: AuthenticatedAppOpsIgLeadHunterRoute,
  AuthenticatedAppOpsLeadInboxRoute: AuthenticatedAppOpsLeadInboxRoute,
  AuthenticatedAppOpsListingClaimsRoute: AuthenticatedAppOpsListingClaimsRoute,
  AuthenticatedAppOpsPlanRequestsRoute: AuthenticatedAppOpsPlanRequestsRoute,
  AuthenticatedAppOpsSiteFooterRoute: AuthenticatedAppOpsSiteFooterRoute,
  AuthenticatedAppOpsSocialLeadHunterRoute:
    AuthenticatedAppOpsSocialLeadHunterRoute,
  AuthenticatedAppSeoCanonicalAuditRoute:
    AuthenticatedAppSeoCanonicalAuditRoute,
  AuthenticatedAppSeoClickReportRoute: AuthenticatedAppSeoClickReportRoute,
  AuthenticatedAppSeoCompetitorRadarRoute:
    AuthenticatedAppSeoCompetitorRadarRoute,
  AuthenticatedAppSeoCompetitorTrackerRoute:
    AuthenticatedAppSeoCompetitorTrackerRoute,
  AuthenticatedAppSeoContentHealthRoute: AuthenticatedAppSeoContentHealthRoute,
  AuthenticatedAppSeoGscImportRoute: AuthenticatedAppSeoGscImportRoute,
  AuthenticatedAppSeoHealthRoute: AuthenticatedAppSeoHealthRoute,
  AuthenticatedAppSeoInternalLinksRoute: AuthenticatedAppSeoInternalLinksRoute,
  AuthenticatedAppSeoKeywordOpportunitiesRoute:
    AuthenticatedAppSeoKeywordOpportunitiesRoute,
  AuthenticatedAppSeoLinkAuditRoute: AuthenticatedAppSeoLinkAuditRoute,
  AuthenticatedAppSeoLinkCheckerRoute: AuthenticatedAppSeoLinkCheckerRoute,
  AuthenticatedAppSeoListingAuditorRoute:
    AuthenticatedAppSeoListingAuditorRoute,
  AuthenticatedAppSeoMissingPagesRoute: AuthenticatedAppSeoMissingPagesRoute,
  AuthenticatedAppSeoPageAuditorRoute: AuthenticatedAppSeoPageAuditorRoute,
  AuthenticatedAppSeoRankTrackerRoute: AuthenticatedAppSeoRankTrackerRoute,
  AuthenticatedAppSeoScrapeImportRoute: AuthenticatedAppSeoScrapeImportRoute,
  AuthenticatedAppSeoSitemapRoute: AuthenticatedAppSeoSitemapRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicDomainTokenRoute: ApiPublicDomainTokenRoute,
  ApiPublicPageLookupRoute: ApiPublicPageLookupRoute,
  ApiPublicSitemapByHostRoute: ApiPublicSitemapByHostRoute,
  ApiPublicHooksCanonicalAuditRoute: ApiPublicHooksCanonicalAuditRoute,
  ApiPublicHooksSyncSharetribeRoute: ApiPublicHooksSyncSharetribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
